### ISSUE TITLE
problem with PyFLEXTRKR

### ISSUE THREAD

**Issue by lbdieng** [FlexTRKR/PyFLEXTRKR#77]
Dear Feng,
Congratulations and gratitude for the incredible tool you have developed and made available to the scientific community.
I find your tool very intriguing, and I am eager to test it in the Senegal region. However, I have encountered difficulties as the script does not seem to be functioning correctly on my machine. Specifically, I attempted to run the demo_mcs_imerg.sh script by adapting the paths accordingly.
As a novice in Python, I have attached the log file for your reference. I would appreciate any assistance or guidance you can provide to resolve this issue. Your expertise in this matter would be invaluable to me.
Please find attached the logfile
[demo_mcs_imerg.log](https://github.com/FlexTRKR/PyFLEXTRKR/files/13793916/demo_mcs_imerg.log)

Thank you in advance for your time and support.

**Comment by feng045** [comment]
Hi,
 
I just pushed an update to PyFLEXTRKR (#78) that should fix this issue.  Please pull the latest codes and give it a try again.
 
Best,
-Zhe

**Comment by feng045** [comment]
I pushed anther update (#79) to fix another similar syntax issue.  The code should work now.  I'm closing this issue.

**Comment by feng045** [comment]
Issue fixed by PR #78 and #79.

**Comment by lbdieng** [comment]
Hi Feng,
Thank you for your quick response,
How I can install the update, I am newer on github

**Comment by lbdieng** [comment]
Hi Feng, 
Thank you for your response, 
the demo demo_mcs_imerg.sh works well (I can get the figures 
![20190125_203000](https://github.com/FlexTRKR/PyFLEXTRKR/assets/58309981/f22e08c6-7b66-4d76-b0a4-8838db5fe8ce)
). However, the demo demo_mcs_wrf_tbpf.sh still doesn't work. Attached is the logfile (
[demo_mcs_wrf_tbpf.log](https://github.com/FlexTRKR/PyFLEXTRKR/files/13798714/demo_mcs_wrf_tbpf.log)

Any idea ?
