### ISSUE TITLE
Issue in running the demo script "demo_cell_csapr.sh"

### ISSUE THREAD

**Issue by jiligulu-cqs** [FlexTRKR/PyFLEXTRKR#85]
Dear author.
I'm trying to run the demo script "demo_cell_csapr.sh",  I modify the dir_demo into the following form, and that's the only change I did to the script.
```
dir_demo='C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config/'
```
But it have some errors, the first unexpected output is
```
2024-03-06 17:22:30,557 - distributed.worker - WARNING - Compute Failed
```
In addition, I noticed in the output, the file path may have double or triple / like "//" or "///", I don't know if this is normal.
Here what I got after running the script
```
Downloading demo input data ...
--2024-03-06 17:18:15--  https://portal.nersc.gov/project/m1867/PyFLEXTRKR/sample_data/radar/taranis_corcsapr2.tar.gz
Resolving portal.nersc.gov (portal.nersc.gov)... 128.55.206.112, 128.55.206.107, 128.55.206.109, ...
Connecting to portal.nersc.gov (portal.nersc.gov)|128.55.206.112|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 451490919 (431M) [application/x-gzip]
Saving to: 'C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config/input//taranis_corcsapr2.tar.gz'

C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/conf 100%[===================================================================================================================>] 430.58M  2.73MB/s    in 3m 44s

2024-03-06 17:22:00 (1.92 MB/s) - 'C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config/input//taranis_corcsapr2.tar.gz' saved [451490919/451490919]

Extracting demo input data ...
x CSAPR2_Taranis_Gridded_500m.Terrain_RangeMask.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.164511_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.170012_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.171503_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.173003_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.174503_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.180003_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.181503_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.183003_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.184503_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.190003_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.191503_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.193003_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.194503_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.200003_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.201503_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.203003_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.204503_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.210003_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.211503_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.213003_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.214503_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.220003_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.221503_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.223003_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.224503_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.230003_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.231503_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.233003_gridded.nc
x taranis_corcsapr2cfrppiqcM1.c1.20190125.234503_gridded.nc
Created new config file: config_cell_demo.yml
Activating PyFLEXTRKR environment ...
Running PyFLEXTRKR ...
2024-03-06 17:22:04,483 - pyflextrkr.idfeature_driver - INFO - Identifying features from raw data
2024-03-06 17:22:04,486 - pyflextrkr.idfeature_driver - INFO - Total number of files to process: 29
2024-03-06 17:22:06,360 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_171503.nc
2024-03-06 17:22:07,704 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_173003.nc
2024-03-06 17:22:08,203 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_194503.nc
2024-03-06 17:22:08,347 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_184503.nc
2024-03-06 17:22:08,790 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_204503.nc
2024-03-06 17:22:09,402 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_164511.nc
2024-03-06 17:22:09,614 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_174503.nc
2024-03-06 17:22:11,932 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_233003.nc
2024-03-06 17:22:12,066 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_190003.nc
2024-03-06 17:22:12,584 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_213003.nc
2024-03-06 17:22:13,258 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_210003.nc
2024-03-06 17:22:14,290 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_180003.nc
2024-03-06 17:22:14,683 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_183003.nc
2024-03-06 17:22:16,101 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_191503.nc
2024-03-06 17:22:16,232 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_230003.nc
2024-03-06 17:22:17,291 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_170012.nc
2024-03-06 17:22:17,830 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_223003.nc
2024-03-06 17:22:18,685 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_214503.nc
2024-03-06 17:22:19,879 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_201503.nc
2024-03-06 17:22:20,551 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_231503.nc
2024-03-06 17:22:21,433 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_220003.nc
2024-03-06 17:22:22,365 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_211503.nc
2024-03-06 17:22:22,694 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_234503.nc
2024-03-06 17:22:24,275 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_221503.nc
2024-03-06 17:22:24,636 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_181503.nc
2024-03-06 17:22:25,383 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_203003.nc
2024-03-06 17:22:25,773 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_224503.nc
2024-03-06 17:22:27,691 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_193003.nc
2024-03-06 17:22:29,416 - pyflextrkr.idcells_reflectivity - INFO - C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_200003.nc
2024-03-06 17:22:29,453 - pyflextrkr.idfeature_driver - INFO - Done with features from raw data.
2024-03-06 17:22:29,454 - __main__ - INFO - Calculating domain mean advection.
2024-03-06 17:22:29,455 - pyflextrkr.advection_tiles - INFO - Found 29 files.
2024-03-06 17:22:30,557 - distributed.worker - WARNING - Compute Failed
Key:       movement_of_storm_fft_l-fb0e0164-aa32-4db2-8451-807290ad7cc8
Function:  execute_task
args:      ((<function apply at 0x000001CF134BB7F0>, <function movement_of_storm_fft_l at 0x000001CF1B16F5B0>, [(<class 'tuple'>, ['C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_180003.nc', 'C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_181503.nc'])], (<class 'dict'>, [['dx', 0.5], ['dy', 0.5], ['config', (<class 'dict'>, [['run_idfeature', True], ['run_advection', True], ['run_tracksingle', True], ['run_gettracks', True], ['run_trackstats', True], ['run_mapfeature', True], ['run_parallel', 1], ['nprocesses', 4], ['dask_tmp_dir', '/tmp'], ['timeout', 360], ['startdate', '20190125.1200'], ['enddate', '20190126.0000'], ['time_format', 'yyyymodd.hhmmss'], ['databasename', 'taranis_corcsapr2cfrppiqcM1.c1.'], ['clouddata_path', 'C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config/input//'], ['root_path', 'C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config//'], ['tracking_path_name', 'tracking'], ['stats_path_name', 'stats
kwargs:    {}
Exception: "ValueError('not enough values to unpack (expected 2, got 0)')"

2024-03-06 17:22:30,560 - distributed.worker - WARNING - Compute Failed
Key:       movement_of_storm_fft_l-f61cb282-4e8c-4679-88ef-1dda814d264c
Function:  execute_task
args:      ((<function apply at 0x00000200BB29B7F0>, <function movement_of_storm_fft_l at 0x00000200C1F7F5B0>, [(<class 'tuple'>, ['C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_164511.nc', 'C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_170012.nc'])], (<class 'dict'>, [['dx', 0.5], ['dy', 0.5], ['config', (<class 'dict'>, [['run_idfeature', True], ['run_advection', True], ['run_tracksingle', True], ['run_gettracks', True], ['run_trackstats', True], ['run_mapfeature', True], ['run_parallel', 1], ['nprocesses', 4], ['dask_tmp_dir', '/tmp'], ['timeout', 360], ['startdate', '20190125.1200'], ['enddate', '20190126.0000'], ['time_format', 'yyyymodd.hhmmss'], ['databasename', 'taranis_corcsapr2cfrppiqcM1.c1.'], ['clouddata_path', 'C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config/input//'], ['root_path', 'C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config//'], ['tracking_path_name', 'tracking'], ['stats_path_name', 'stats
kwargs:    {}
Exception: "ValueError('not enough values to unpack (expected 2, got 0)')"

Traceback (most recent call last):
2024-03-06 17:22:30,571 - distributed.worker - WARNING - Compute Failed
Key:       movement_of_storm_fft_l-fb23b742-d15d-46c8-ac83-2240592d996a
Function:  execute_task
args:      ((<function apply at 0x0000020662EBB7F0>, <function movement_of_storm_fft_l at 0x000002066AB6F5B0>, [(<class 'tuple'>, ['C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_221503.nc', 'C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_223003.nc'])], (<class 'dict'>, [['dx', 0.5], ['dy', 0.5], ['config', (<class 'dict'>, [['run_idfeature', True], ['run_advection', True], ['run_tracksingle', True], ['run_gettracks', True], ['run_trackstats', True], ['run_mapfeature', True], ['run_parallel', 1], ['nprocesses', 4], ['dask_tmp_dir', '/tmp'], ['timeout', 360], ['startdate', '20190125.1200'], ['enddate', '20190126.0000'], ['time_format', 'yyyymodd.hhmmss'], ['databasename', 'taranis_corcsapr2cfrppiqcM1.c1.'], ['clouddata_path', 'C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config/input//'], ['root_path', 'C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config//'], ['tracking_path_name', 'tracking'], ['stats_path_name', 'stats
kwargs:    {}
Exception: "ValueError('not enough values to unpack (expected 2, got 0)')"

2024-03-06 17:22:30,573 - distributed.worker - WARNING - Compute Failed
Key:       movement_of_storm_fft_l-f6cb6cc8-c80a-45d7-96bc-390168ed4873
Function:  execute_task
args:      ((<function apply at 0x00000176A0ADB7F0>, <function movement_of_storm_fft_l at 0x00000176A779F5B0>, [(<class 'tuple'>, ['C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_183003.nc', 'C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_184503.nc'])], (<class 'dict'>, [['dx', 0.5], ['dy', 0.5], ['config', (<class 'dict'>, [['run_idfeature', True], ['run_advection', True], ['run_tracksingle', True], ['run_gettracks', True], ['run_trackstats', True], ['run_mapfeature', True], ['run_parallel', 1], ['nprocesses', 4], ['dask_tmp_dir', '/tmp'], ['timeout', 360], ['startdate', '20190125.1200'], ['enddate', '20190126.0000'], ['time_format', 'yyyymodd.hhmmss'], ['databasename', 'taranis_corcsapr2cfrppiqcM1.c1.'], ['clouddata_path', 'C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config/input//'], ['root_path', 'C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config//'], ['tracking_path_name', 'tracking'], ['stats_path_name', 'stats
kwargs:    {}
Exception: "ValueError('not enough values to unpack (expected 2, got 0)')"

  File "C:\Users\user\Desktop\downloads\PyFLEXTRKR-main\runscripts\run_celltracking.py", line 49, in <module>
    driftfile = calc_mean_advection(config)
  File "c:\users\user\miniconda3\envs\pyflextrkr\pyflextrkr\advection_tiles.py", line 296, in calc_mean_advection
    final_results = dask.compute(*results)
  File "C:\Users\user\miniconda3\envs\flextrkr\lib\site-packages\dask\base.py", line 661, in compute
    results = schedule(dsk, keys, **kwargs)
  File "c:\users\user\miniconda3\envs\pyflextrkr\pyflextrkr\advection_tiles.py", line 213, in movement_of_storm_fft_l
    y1, x1 = movement_of_storm_fft(
  File "c:\users\user\miniconda3\envs\pyflextrkr\pyflextrkr\advection_tiles.py", line 159, in movement_of_storm_fft
    y, x = -1 * phase_cross_correlation(
ValueError: not enough values to unpack (expected 2, got 0)
2024-03-06 17:22:30,607 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('movement_of_storm_fft_l-c236b978-1ed3-4023-870f-a16a7083a487')" coro=<Worker.execute() done, defined at C:\Users\user\miniconda3\envs\flextrkr\lib\site-packages\distributed\worker_state_machine.py:3615>> ended with CancelledError
2024-03-06 17:22:30,608 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('movement_of_storm_fft_l-bf1c49ef-0141-4037-96f6-0a91df2f71f2')" coro=<Worker.execute() done, defined at C:\Users\user\miniconda3\envs\flextrkr\lib\site-packages\distributed\worker_state_machine.py:3615>> ended with CancelledError
2024-03-06 17:22:30,608 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('movement_of_storm_fft_l-f0ee9b6e-9a52-4b1b-acff-f34146e88f8c')" coro=<Worker.execute() done, defined at C:\Users\user\miniconda3\envs\flextrkr\lib\site-packages\distributed\worker_state_machine.py:3615>> ended with CancelledError
2024-03-06 17:22:30,609 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('movement_of_storm_fft_l-ba616717-1c89-407e-b216-23ed615b8715')" coro=<Worker.execute() done, defined at C:\Users\user\miniconda3\envs\flextrkr\lib\site-packages\distributed\worker_state_machine.py:3615>> ended with CancelledError
Tracking is done.
Making quicklook plots ...
Number of pixel files: 0
Traceback (most recent call last):
  File "C:\Users\user\miniconda3\envs\flextrkr\lib\site-packages\xarray\backends\file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "C:\Users\user\miniconda3\envs\flextrkr\lib\site-packages\xarray\backends\lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('C:\\Users\\user\\Desktop\\downloads\\PyFLEXTRKR-main\\config\\stats\\trackstats_20190125.1200_20190126.0000.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'eab827b8-baed-48be-abac-49ac155e931e']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\downloads\PyFLEXTRKR-main\Analysis\plot_subset_cell_tracks_demo.py", line 611, in <module>
    track_dict = get_track_stats(trackstats_file, start_datetime, end_datetime, dt_thres)
  File "C:\Users\user\Desktop\downloads\PyFLEXTRKR-main\Analysis\plot_subset_cell_tracks_demo.py", line 176, in get_track_stats
    dss = xr.open_dataset(trackstats_file)
  File "C:\Users\user\miniconda3\envs\flextrkr\lib\site-packages\xarray\backends\api.py", line 573, in open_dataset
    backend_ds = backend.open_dataset(
  File "C:\Users\user\miniconda3\envs\flextrkr\lib\site-packages\xarray\backends\netCDF4_.py", line 646, in open_dataset
    store = NetCDF4DataStore.open(
  File "C:\Users\user\miniconda3\envs\flextrkr\lib\site-packages\xarray\backends\netCDF4_.py", line 409, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "C:\Users\user\miniconda3\envs\flextrkr\lib\site-packages\xarray\backends\netCDF4_.py", line 356, in __init__
    self.format = self.ds.data_model
  File "C:\Users\user\miniconda3\envs\flextrkr\lib\site-packages\xarray\backends\netCDF4_.py", line 418, in ds
    return self._acquire()
  File "C:\Users\user\miniconda3\envs\flextrkr\lib\site-packages\xarray\backends\netCDF4_.py", line 412, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "C:\Users\user\miniconda3\envs\flextrkr\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\user\miniconda3\envs\flextrkr\lib\site-packages\xarray\backends\file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "C:\Users\user\miniconda3\envs\flextrkr\lib\site-packages\xarray\backends\file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src\netCDF4\_netCDF4.pyx", line 2449, in netCDF4._netCDF4.Dataset.__init__
  File "src\netCDF4\_netCDF4.pyx", line 2012, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\Desktop\\downloads\\PyFLEXTRKR-main\\config\\stats\\trackstats_20190125.1200_20190126.0000.nc'
View quicklook plots here: C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config//quicklooks_trackpaths/
Making animations from quicklook plots ...
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[image2 @ 0000022c12d613c0] Pattern type 'glob' was selected but globbing is not supported by this libavformat build
C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config//quicklooks_trackpaths/*.png: Function not implemented
View animation here: C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config//quicklooks_trackpaths/quicklook_animation.mp4
Demo completed!
```

**Comment by feng045** [comment]
Hi. I'm aware of this issue due to the newer version (> 0.20) of Scikit-image phase_cross_correlation function returning 3 variables instead of one.  I am planning to issue a PR to fix this issue in the next few days.  In the mean time, if you want to proceed with the current version, you can modify [Line 159 in /pyflextrkr/advection_tiles.py](https://github.com/FlexTRKR/PyFLEXTRKR/blob/6236b0a1a18bdddac8acccb8a7a2f127497fa613/pyflextrkr/advection_tiles.py#L159) by adding `[0]` after the function to catch its first return variable as follows:

```
y, x = -1 * phase_cross_correlation(
                field_1, field_2, reference_mask=mask_1t, moving_mask=mask_2t, overlap_ratio=0.7
            )[0]
```

That should fix the issue for now.  The PR will address this more comprehensively by checking the version of Scikit-image.

**Comment by jiligulu-cqs** [comment]
Thanks for your response!
I modified the code based on your suggestion, but it still have the same output, I guess there are other code files that also used that function.
So I downgrade scikit-image to version 0.19.3, it can operate normally (I see pictures in quicklooks_trackpaths). But there are still two unexpected outputs.
### 1.  HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 12284:
This output was generate during the 'Running PyFLEXTRKR' procedure, and it output many times. 
The thread number may different, but seems all related to 'can't open attribute'.
```
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 12284:
  #000: D:\bld\hdf5_split_1671624031008\work\src\H5A.c line 528 in H5Aopen_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #001: D:\bld\hdf5_split_1671624031008\work\src\H5VLcallback.c line 1091 in H5VL_attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #002: D:\bld\hdf5_split_1671624031008\work\src\H5VLcallback.c line 1058 in H5VL__attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: D:\bld\hdf5_split_1671624031008\work\src\H5VLnative_attr.c line 130 in H5VL__native_attr_open(): can't open attribute
    major: Attribute
    minor: Can't open object
  #004: D:\bld\hdf5_split_1671624031008\work\src\H5Aint.c line 545 in H5A__open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #005: D:\bld\hdf5_split_1671624031008\work\src\H5Oattribute.c line 494 in H5O__attr_open_by_name(): can't locate attribute: '_QuantizeBitGroomNumberOfSignificantDigits'
    major: Attribute
    minor: Object not found
    minor: Object not found
```
### 2.  double or triple / in file path in the output
Like this, between 'config' and 'tracking'
```
C:/Users/user/Desktop/downloads/PyFLEXTRKR-main/config///tracking/cloudid_20190125_210003.nc
```
It seems does not affect the results, but this may be the cause of the previous question, this is just my guess.

**Comment by travis-j-hahn** [comment]
Hi, 

The issue seems to be with your HDF4/5 versions interacting with libnetcdf. It looks like it began with HDF5 v12.2 as you can read about here: (https://github.com/SciTools/iris/issues/5187). I would try updating hdf4, hdf5, and libnetcdf to versions 4.2.15, 1.13.3, and 4.9.2, respectively--this is the configuration that worked for me using Windows 10.

**Comment by feng045** [comment]
Hi,

The compatibility issue with Scikit-image >= 0.22 should now be resolved with the release [2024.03.0](https://github.com/FlexTRKR/PyFLEXTRKR/releases/tag/2024.03.0).

I tried setting up a new Conda environment with the updated [environment.yml](https://github.com/FlexTRKR/PyFLEXTRKR/blob/main/environment.yml) and current latest versions of the required [packages](https://github.com/FlexTRKR/PyFLEXTRKR/blob/main/requirements.txt), the codes all run well.

Try re-installing PyFLEXTRKR with the current release and see if it works for you.

**Comment by jiligulu-cqs** [comment]
> Hi,
> 
> The issue seems to be with your HDF4/5 versions interacting with libnetcdf. It looks like it began with HDF5 v1.12.2 as you can read about here: ([SciTools/iris#5187](https://github.com/SciTools/iris/issues/5187)). I would try updating hdf4, hdf5, and libnetcdf to versions 4.2.15, 1.13.3, and 4.9.2, respectively--this is the configuration that worked for me using Windows 10.

Thanks for your reply! It's fixed base on your suggestion. (using Windows 11)

**Comment by jiligulu-cqs** [comment]
> Hi,
> 
> The compatibility issue with Scikit-image >= 0.22 should now be resolved with the release [2024.03.0](https://github.com/FlexTRKR/PyFLEXTRKR/releases/tag/2024.03.0).
> 
> I tried setting up a new Conda environment with the updated [environment.yml](https://github.com/FlexTRKR/PyFLEXTRKR/blob/main/environment.yml) and current latest versions of the required [packages](https://github.com/FlexTRKR/PyFLEXTRKR/blob/main/requirements.txt), the codes all run well.
> 
> Try re-installing PyFLEXTRKR with the current release and see if it works for you.

Thanks again!
Now the codes run well.
